# Generated by Django 5.1.5 on 2025-02-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_customerprofile_age_customerprofile_allergies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='profile_complete',
            field=models.BooleanField(default=False),
        ),
    ]
