# Generated by Django 5.1.5 on 2025-03-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_customerprofile_profile_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
